export const ImagePath = {
  APPLOGO: require('../assets/images/AppLogo.jpeg'),
  BRAND: require('../assets/images/brand.png'),
  CHRISTMAS: require('../assets/images/christmas.png'),
  CUTWITH: require('../assets/images/cut-with-scissors.png'),
  ECO: require('../assets/images/eco-product.png'),
  EMBROIDERY: require('../assets/images/embroidery.png'),
  FABRIC: require('../assets/images/fabric.png'),
  FASHION: require('../assets/images/fashion.png'),
  HAND: require('../assets/images/hand.png'),
  HEAT: require('../assets/images/heat.png'),
  MANNEQUIN: require('../assets/images/mannequin.png'),
  SCREEN: require('../assets/images/screen.png'),
  SEWING: require('../assets/images/sewing-machine.png'),
  SWIMWEAR: require('../assets/images/swimwear.png'),
  WARDROBE: require('../assets/images/wardrobe.png'),
  WORKOUT: require('../assets/images/workout-clothes.png'),
};
